version: '3'

services:
  user-service:
    build: .
    command: ./.docker/start.sh
    networks:
      - partyu_network
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/user-service
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    networks:
      - partyu_network
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

networks:
  partyu_network:
    external: true

volumes:
  mongodb_data:
